version: '3.8'
services:
  # Backend API service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
      - minio
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sih}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sih}
      POSTGRES_DB: ${POSTGRES_DB:-sih}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    restart: unless-stopped

  # Database Admin Interface
  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: {}
  redis_data: {}
  minio_data: {}

